### ISSUE TITLE
Integration with Vaadin 8

### ISSUE THREAD

**Issue by vimalkumar010** [iSergio/gwt-cs#11]
Hi, Sergio
       We are doing our project on Vaadin 8. Is it possible to include the Cesiumjs4gwt inside Vaadin 8 Application...?

When i try to put the ViewerPanel in MyUI class, then i'm getting the following error. Is it possible to resolve this error...?

Your comments and suggestion are much appreciated...
Thanks...

java.lang.NoClassDefFoundError: org/cesiumjs/cs/widgets/ViewerPanel
	at com.company.MyUI$MyUIServlet.<init>(MyUI.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2470)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1327)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1220)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:496)
	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:788)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:773)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:578)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.cesiumjs.cs.widgets.ViewerPanel
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
	... 37 more
Caused by:
java.lang.ClassNotFoundException: org.cesiumjs.cs.widgets.ViewerPanel
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
	at com.company.MyUI$MyUIServlet.<init>(MyUI.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2470)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1327)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1220)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:496)
	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:788)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:773)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:578)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)

**Comment by iSergio** [comment]
Hi
How I remember, Vaadin is server side compile UI components... This error is mean, java not found sources in server side, to fix them you should add sources.jar to project (<img width="927" alt="Снимок экрана 2019-07-12 в 10 21 38" src="https://user-images.githubusercontent.com/12247944/61110126-30f2ae00-a48f-11e9-8c70-e2bcc7273ead.png">)... This error removed. But, after this wee get error on GWT.create() on server side:
`java.lang.UnsupportedOperationException: ERROR: GWT.create() is only usable in client code!  It cannot be called, for example, from server code.  If you are running a unit test, check that your test case extends GWTTestCase and that GWT.create() is not called from within an initializer or constructor.`
For use GWT thirdparty in Vaadin - https://vaadin.com/docs/v8/framework/articles/IntegratingAnExistingGWTWidget.html
I'll try test how this work in Vaadin on weekend

**Comment by iSergio** [comment]
Hi!
How I remember, Vaadin is server side compile UI components... This error is mean, java not found sources in server side, to fix them you should add sources.jar to project ( <https://user-images.githubusercontent.com/12247944/61110126-30f2ae00-a48f-11e9-8c70-e2bcc7273ead.png>)... This error removed. But, after this wee get error on GWT.create() on server side:
java.lang.UnsupportedOperationException: ERROR: GWT.create() is only usable in client code! It cannot be called, for example, from server code. If you are running a unit test, check that your test case extends GWTTestCase and that GWT.create() is not called from within an initializer or constructor.
For use GWT thirdparty in Vaadin - https://vaadin.com/docs/v8/framework/articles/IntegratingAnExistingGWTWidget.html <https://vaadin.com/docs/v8/framework/articles/IntegratingAnExistingGWTWidget.html>
I'll try test how this work in Vaadin on weekend
------------------------------------------------------------------------------
С уважением, Сергей Борисович

**Comment by iSergio** [comment]
And CesiumJS code inject to application over extends GWT AbstractLinker... I can not imagine how it will work in Vaadin server side ui. Maybe this can fix if use bundle loader

**Comment by vimalkumar010** [comment]
Hi, 
   And Thanks for trying with Vaadin, And its very appreciable... It will be very useful to create a Vaadin Component using Cesiumjs4gwt. Hoping for a positive outcome on your research on Vaadin in the weekend...
Thanks Sergio...

**Comment by vimalkumar010** [comment]
Hi Sergio,
              Is that any update on Cesiums4gwt inside Vaadin...? Did you managed to get it running...?

**Comment by iSergio** [comment]
Sorry, i tried write wrapper on Vaadin 8 by they documentation, but not success, they code in example not worked ( I will be try later, on this moment many main work tasks

**Comment by vimalkumar010** [comment]
Dear Sergio,
                 We are looking to integrate the cesiumjs4gwt into Vaadin 8 Application. So, as you know we need to create a Vaadin component. So, Is it possible for you to create a Vaadin 8 Component for this cesiumjs4GWT. We are very much interested to buy the Component. You can also quote your pricing to develop the component. Can you please reply me back to my email....

Thanks Sergio...
